### ISSUE TITLE
"Operation not supported" in perf_event_wrapper.cpp(345) error

### ISSUE THREAD

**Issue by cztchoice** [uart/scarphase#1]
when i run the example profile command, i encounter an error:

```
$ ./scarphase profile --scarphase-conf configs/scarphase/example0.conf --counter-conf configs/counters/list0.json --counter-limit=1 gcc.profile -- /bin/ls
4 72 1220 1 1 1
Operation not supported
/home/choice/github/scarphase/libscarphase/source/scarphase/internal/util/perf_event_wrapper.cpp(345): Throw in function int scarphase::internal::util::perf_event_wrapper::open(perf_event_attr&, pid_t, int, int, long unsigned int)
Dynamic exception type: boost::exception_detail::clone_impl<scarphase::internal::util::perf_event_wrapper::PerfEventError>
std::exception::what: std::exception
[boost::errinfo_errno_*] = 95, "Operation not supported"
[boost::errinfo_api_function_*] = syscall

terminate called after throwing an instance of 'boost::exception_detail::clone_impl<scarphase::internal::util::perf_event_wrapper::PerfEventError>'
  what():  std::exception
Aborted (core dumped)
```

the second line of the message is the output i add  the follow line in the perf_event_wrapper::open function:

```
printf("%d %d %d %d %d %d\n", attr.type, attr.size, attr.config, attr.disabled, attr.exclude_kernel, attr.exclude_hv);
```

I think it was because the perf event is not support in my computer at first. 
but when i changed the counter config in configs/scarphase/example0.conf:87, make the counter use 0x1, which is supported by my machine, the error still exists.

I also use root to run the command, the error is still there.

I have no idea about it, can you give me some suggestions about how to deal with it?

My cpu is: Intel(R) Core(TM) i5-2300 CPU @ 2.80GHz， and my os is Ubuntu 12.04, if you need any other info about my machine, just tell me.

Thanks.

**Comment by zaxfenfeiyu** [comment]
I also meet this problem, is that mean I can't use this software to detect? I turn off PEBS, and then it works, but there is no data in XXX.profile.
